// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5yddtE5x1v-nO2HgT_eLLY5BYG0XpNGE',
    appId: '1:574831664093:web:24a99ea4fc8894c4f07434',
    messagingSenderId: '574831664093',
    projectId: 'smartbillingsys',
    authDomain: 'smartbillingsys.firebaseapp.com',
    storageBucket: 'smartbillingsys.firebasestorage.app',
    measurementId: 'G-VG9P8K536C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlWvHNZtVsEViai-r_xrIS--dLUbZ_QnQ',
    appId: '1:574831664093:android:dc3feb0e917616cff07434',
    messagingSenderId: '574831664093',
    projectId: 'smartbillingsys',
    storageBucket: 'smartbillingsys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXJh4uPbegFJ8-tDJ93Rbr9vBxAyvP3Us',
    appId: '1:574831664093:ios:deb29414d9c4aea8f07434',
    messagingSenderId: '574831664093',
    projectId: 'smartbillingsys',
    storageBucket: 'smartbillingsys.firebasestorage.app',
    iosBundleId: 'com.example.smartbilling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXJh4uPbegFJ8-tDJ93Rbr9vBxAyvP3Us',
    appId: '1:574831664093:ios:deb29414d9c4aea8f07434',
    messagingSenderId: '574831664093',
    projectId: 'smartbillingsys',
    storageBucket: 'smartbillingsys.firebasestorage.app',
    iosBundleId: 'com.example.smartbilling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5yddtE5x1v-nO2HgT_eLLY5BYG0XpNGE',
    appId: '1:574831664093:web:b33f027006981bfcf07434',
    messagingSenderId: '574831664093',
    projectId: 'smartbillingsys',
    authDomain: 'smartbillingsys.firebaseapp.com',
    storageBucket: 'smartbillingsys.firebasestorage.app',
    measurementId: 'G-PHWPD3MZ10',
  );

}