import 'dart:io';
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

/// Service to generate preview images for invoice templates
/// Note: This creates placeholder previews. Actual PDF generation uses the real templates.
class TemplatePreviewGenerator {
  /// Generate preview image for a template
  static Future<String?> generatePreview(String templateKey) async {
    try {
      // Create a placeholder preview image
      final targetWidth = 800.0;
      final targetHeight = 1131.0; // A4 ratio

      final recorder = ui.PictureRecorder();
      final canvas = Canvas(recorder);

      // White background
      final paint = Paint()
        ..color = Colors.white
        ..style = PaintingStyle.fill;
      canvas.drawRect(
        Rect.fromLTWH(0, 0, targetWidth, targetHeight),
        paint,
      );

      // Draw template label with styling based on template
      final templateName = 'Template $templateKey';
      final templateDesc = _getTemplateDescription(templateKey);
      final templateColor = _getTemplateColor(templateKey);

      // Draw header bar
      final headerPaint = Paint()
        ..color = templateColor
        ..style = PaintingStyle.fill;
      canvas.drawRect(
        Rect.fromLTWH(0, 0, targetWidth, 100),
        headerPaint,
      );

      // Draw template name
      final namePainter = TextPainter(
        text: TextSpan(
          text: templateName,
          style: TextStyle(
            color: Colors.white,
            fontSize: 32,
            fontWeight: FontWeight.bold,
          ),
        ),
        textDirection: ui.TextDirection.ltr,
        textAlign: TextAlign.center,
      );
      namePainter.layout(maxWidth: targetWidth);
      namePainter.paint(
        canvas,
        Offset(
          (targetWidth - namePainter.width) / 2,
          20,
        ),
      );

      // Draw description
      final descPainter = TextPainter(
        text: TextSpan(
          text: templateDesc,
          style: TextStyle(
            color: Colors.white70,
            fontSize: 16,
          ),
        ),
        textDirection: ui.TextDirection.ltr,
        textAlign: TextAlign.center,
      );
      descPainter.layout(maxWidth: targetWidth);
      descPainter.paint(
        canvas,
        Offset(
          (targetWidth - descPainter.width) / 2,
          60,
        ),
      );

      // Draw preview content area
      final contentPaint = Paint()
        ..color = Colors.grey.shade100
        ..style = PaintingStyle.fill;
      canvas.drawRect(
        Rect.fromLTWH(20, 120, targetWidth - 40, targetHeight - 140),
        contentPaint,
      );

      // Draw sample invoice elements
      final sampleText = TextPainter(
        text: TextSpan(
          text: 'Invoice Preview\n\nSample Invoice Content\n\nItems • Totals • Details',
          style: TextStyle(
            color: Colors.grey.shade700,
            fontSize: 18,
            fontWeight: FontWeight.w500,
          ),
        ),
        textDirection: ui.TextDirection.ltr,
        textAlign: TextAlign.center,
      );
      sampleText.layout(maxWidth: targetWidth - 40);
      sampleText.paint(
        canvas,
        Offset(
          20 + (targetWidth - 40 - sampleText.width) / 2,
          120 + (targetHeight - 140 - sampleText.height) / 2,
        ),
      );

      // Convert to image (must be done on UI thread)
      final picture = recorder.endRecording();
      
      // picture.toImage() requires UI context - this should work if called from a widget
      ui.Image image;
      try {
        image = await picture.toImage(
          targetWidth.toInt(),
          targetHeight.toInt(),
        );
      } catch (e) {
        debugPrint('❌ Error converting picture to image for $templateKey: $e');
        debugPrint('This might need to run on the UI thread');
        return null;
      }

      // Convert to PNG bytes
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      if (byteData == null) {
        debugPrint('❌ Failed to convert image to byte data for $templateKey');
        return null;
      }
      
      final imageBytes = byteData.buffer.asUint8List();
      
      if (imageBytes.isEmpty) {
        debugPrint('❌ Generated image bytes are empty for $templateKey');
        return null;
      }
      
      // Verify it's a valid PNG (starts with PNG signature)
      if (imageBytes.length < 8 || 
          imageBytes[0] != 0x89 || 
          imageBytes[1] != 0x50 || 
          imageBytes[2] != 0x4E || 
          imageBytes[3] != 0x47) {
        debugPrint('❌ Generated bytes are not a valid PNG for $templateKey');
        return null;
      }
      
      debugPrint('✅ Generated ${imageBytes.length} bytes for preview $templateKey');

      // Save to local storage
      final dir = await getApplicationDocumentsDirectory();
      final previewDir = Directory(p.join(dir.path, 'pdf_previews'));
      if (!await previewDir.exists()) {
        await previewDir.create(recursive: true);
      }

      final fileName = 'preview_$templateKey.png';
      final filePath = p.join(previewDir.path, fileName);
      final file = File(filePath);
      await file.writeAsBytes(imageBytes);

      debugPrint('✅ Preview generated for template $templateKey: $filePath');
      return filePath;
    } catch (e) {
      debugPrint('❌ Error generating preview for $templateKey: $e');
      return null;
    }
  }

  /// Get template description
  static String _getTemplateDescription(String key) {
    switch (key.toUpperCase()) {
      case 'A':
        return 'Standard GST layout with left-aligned header';
      case 'B':
        return 'Minimal design with centered header';
      case 'C':
        return 'Premium blue with gradient header';
      case 'E':
        return 'Modern minimal with clean lines';
      default:
        return 'Invoice Template';
    }
  }

  /// Get template color
  static Color _getTemplateColor(String key) {
    switch (key.toUpperCase()) {
      case 'A':
        return const Color(0xFF1976D2); // Blue
      case 'B':
        return const Color(0xFF4CAF50); // Green
      case 'C':
        return const Color(0xFF9C27B0); // Purple
      case 'E':
        return const Color(0xFFFF9800); // Orange
      default:
        return Colors.grey;
    }
  }
}
